/* This file is automatically generated by NRPy+. Do not edit. */

/* EVOLVED VARIABLES: */
#define NUM_EVOL_GFS 28
#define RADIUSGF	0
#define RPRIMEGF	1
#define BBGF	2
#define BPGF	3
#define CHIGF	4
#define CHIPGF	5
#define CHIPPGF	6
#define COSTHGF	7
#define FGAUGEGF	8
#define FGAUGEPGF	9
#define GGGF	10
#define GPGF	11
#define PSIBD0GF	12
#define PSIBD1GF	13
#define PSIBD2GF	14
#define PSIFD0GF	15
#define PSIFD1GF	16
#define PSIFD2GF	17
#define PSIGD0GF	18
#define PSIGD1GF	19
#define PSIGD2GF	20
#define PSIUD0GF	21
#define PSIUD1GF	22
#define PSIUD2GF	23
#define RCOORDGF	24
#define SINTHGF	25
#define UPGF	26
#define UUGF	27


/* AUXILIARY VARIABLES: */
#define NUM_AUX_GFS 12
#define CDB0GF	0
#define CDB1GF	1
#define CDB2GF	2
#define CDF0GF	3
#define CDF1GF	4
#define CDF2GF	5
#define CDG0GF	6
#define CDG1GF	7
#define CDG2GF	8
#define CDU0GF	9
#define CDU1GF	10
#define CDU2GF	11


/* AUXEVOL VARIABLES: */
#define NUM_AUXEVOL_GFS 0


/* PARITY TYPES FOR ALL GRIDFUNCTIONS.
   SEE "Tutorial-Start_to_Finish-Curvilinear_BCs.ipynb" FOR DEFINITIONS. */
const int8_t evol_gf_parity[28] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 0, 0, 0, 0 };
const int8_t aux_gf_parity[12] = { 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3 };
